name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
    # cron: '00 15 * * *'로 하면 한국 시간 기준으로 오전 12:00에 업데이트 된다
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # 플래그 자리
          LOCALE: "ko" #한국
          SHOW_SHORT_INFO: "False" # 사용자의 짧은 재미있는 사실 정보
          SHOW_PROFILE_VIEWS: "False" # 프로필 커밋 수 
          SHOW_LINES_OF_CODE: "False" 
          SHOW_LOC_CHART: "False" # 다른 연도의 다른 분기에 작성된 코드
          SHOW_PROJECTS: "False"  # 작업한 프로젝트
          SHOW_LANGUAGE_PER_REPO: "False" # 사용하는 다양한 언어 및 프레임워크
          SHOW_LANGUAGE: "False" # 사용하는 코딩 언어
          SHOW_OS: "False"
          SHOW_EDITORS: "False" # 사용된 코드 편집기
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_UPDATED_DATE: "False"
          COMMIT_MESSAGE: "Updated with Waka Readme"
          SHOW_COMMIT: "True" # Morning  
          SHOW_DAYS_OF_WEEK: "True" # Monday
          SHOW_TIMEZONE: "False" # 시간대
          SYMBOL_VERSION: 3
          DEBUG_LOGGING: "False" # 언어별 타임라인 추가
